---
resources: 
# resource for my GitHub repo
- name: concourse-boot-sample
  type: git
  source:
    uri: https://github.com/sabbyanandan/concourse-booter.git
    branch: master
    
jobs:
- name: build-binary
  plan:
    - get: concourse-boot-sample
      trigger: true
    - task: build-task
      privileged: true
      file: concourse-boot-sample/build.yml
