---
resources: 
# resource for my GitHub repo
- name: the-gitrigger
  type: git
  source:
    uri: https://github.com/sabbyanandan/concourse-booter.git
    branch: master
# resource for my docker repo
- name: the-docker-image
  type: docker-image
  privileged: true
  source:
    repository: sabby/concourse-boot-sample
    tag: latest
    
jobs:
- name: build-the-binary
  plan:
    # pull code
    - get: the-gitrigger
      trigger: true
    # build code
    - task: build-task
      privileged: true
      file: concourse-boot-sample/build.yml
    # automatically change version
    # - task: update-ship-it-job-name
    #   config:
    #     platform: linux
    #     image_resource: 
    #       type: docker-image
    #       source:
    #         repository: maven
    #         tag: latest
    #     inputs:
    #       - name: fly-release
    #     outputs:
    #       - name: email-text
    #     run:
    #       path: sh
    #       args:
    #       - -exc
    #       - |
    #         export LATEST_GOOD_VERSION=$(cat ./fly-release/version)
    #         echo "Version $LATEST_GOOD_VERSION is ready to ship!"
    #         mv ./fly-release/fly_linux_amd64 ./fly
    #         chmod +x ./fly
    #         ./fly -t local login -c {{concourse-url}} -n {{concourse-team}} #-u {{concourse-username}} -p {{concourse-password}}
    #         ./fly -t local sync
    #         ./fly -t local get-pipeline -p {{concourse-pipeline-name}} > ./original-pipeline.yml
    #         sed "s/Ship-version-.*/Ship-version-$LATEST_GOOD_VERSION/" ./original-pipeline.yml > ./updated-pipeline.yml
    #         ./fly -t local set-pipeline -p {{concourse-pipeline-name}} -c ./updated-pipeline.yml -n  
    # dockerize code
    - put: the-docker-image
      params: 
        # file: foo-app/target/concourse-boot-sample-0.0.1-SNAPSHOT.jar
        foo: Ship-version-0.0.1-SNAPSHOT.jar

caches:
  - path: .gradle/
  - path: .m2/