---
platform: linux

image_resource: 
  type: docker-image
  source: {repository: docker, tag: dind, repository: maven, tag: latest}
    
inputs:
  - name: the-gitrigger
  
outputs:
  - name: foo-app
  
run:
  path: the-gitrigger/build.sh