---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: amidos/dcind
    
inputs:
  - name: the-gitrigger
  
outputs:
  - name: foo-app
  
run:
  path: the-gitrigger/build.sh