---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: amidos/dcind
    
inputs:
  - name: the-gitrigger
  
outputs:
  - name: foo-app
  
run:
  path: sh
  args:
    - -exc
    - |
    
    # export ROOT_FOLDER=$( pwd )
    # export REPO=repo

    
    source /docker-lib.sh
    start_docker
    

    
    docker images

    . the-gitrigger/generate-settings.sh

    git clone the-gitrigger foo-app

    cd foo-app

    ./mvnw package docker:build