---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: maven
    tag: latest
    repository: docker
    tag: dind
    
inputs:
  - name: the-gitrigger
  
outputs:
  - name: foo-app
  
run:
  path: the-gitrigger/build.sh