---
resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: springio/artifactory-resource
    tag: 0.0.3

resources: 
- name: alpine-latest
  type: docker-image
  source:
    repository: alpine
    tag:        latest

- name: artifactory-repo
  type: artifactory-resource
  source:
    uri: ((artifactory_uri))
    username: ((artifactory_username))
    password: ((artifactory_password))
    build_name: concourse-booter

- name: concourse-booter
  type: git
  source:
    uri: https://github.com/sabbyanandan/concourse-booter.git
    branch: master
    ignore_paths:
    - ci/docker-image/*

- name: concourse-booter-latest
  type: docker-image
  source:
    repository: sabby/concourse-booter
    username:   ((docker_username))
    password:   ((docker_password))

- name: concourse-booter-register-latest
  type: docker-image
  source:
    repository: sabby/concourse-booter-register
    username:   ((docker_username))
    password:   ((docker_password))

- name: docker-image
  type: git
  source:
    uri:    https://github.com/sabbyanandan/concourse-booter.git
    branch: master
    paths:
    - ci/docker-image/*

jobs:
- name: build
  serial: true
  public: true
  plan:
  - get: concourse-booter
    trigger: true
  - task: build
    file: concourse-booter/ci/deploy.yml
  - aggregate:
    - put: artifactory-repo
      params:
        repo: libs-snapshot-local
        build_number: "${BUILD_ID}"
        folder: distribution-repository
        build_uri: "${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
        disable_checksum_uploads: true
        # debug: true 
    - put: concourse-booter-latest
      params:
        build: docker-image


- name: docker-image
  public: true
  plan:
  - aggregate:
    - get: docker-image
      trigger: true
    - get: alpine-latest
      trigger: true
  - put: concourse-booter-register-latest
    params:
      build: docker-image/ci/docker-image

- name: register
  serial: true
  public: true
  plan:
  - aggregate:
    - get: concourse-booter
      passed:
      - build
    - get: distribution-repository
      resource: artifactory-repo
      trigger: true
      passed:
      - build
      params:
        generate_maven_metadata: true
  - task: register
    file: concourse-booter/ci/register.yml
